#!/bin/zsh

# Display current directory($1 arg) and git status
#
# Do following setups to use
#   1. make this script executable with `$ chmod u+x`
#   1. create alias of this script in /usr/local/bin
#     - `$ ln -s ~/dotfiles/setup_scripts/tmux/tmux-pane-info /usr/local/bin/tmux-pane-info`
#   1. call this script from `.tmux.conf` like following
#     - `set -g pane-border-format "#(tmux-pane-border '#{pane_current_path}')"`
if git_status=$(cd $1 && git --no-optional-locks status 2>/dev/null ); then
  git_branch="$(echo $git_status| awk 'NR==1 {print $3}')"
  case $git_status in
    *nothing\ to*    ) state="#[fg=black,bg=green]" ;;
    *nothing\ added* ) state="#[fg=black,bg=yellow]" ;;
    *#\ Untracked*   ) state="#[fg=black,bg=red]" ;; 
                   * ) state="#[fg=black,bg=red]" ;;
  esac
  git_info="${state} ${git_branch} "
else
  git_info=""
fi

# if directory uses git.
if [ -n "$git_info" ]; then
  # There's a 20% chance that you get PR CI and Review status. becauese API requeting is so expensive.
  if [ $(($RANDOM % 100)) -lt 20 ]; then
    # Get PR ID with branch, then Get PR CI and Review status, using GitHub API
    pr_id=$(cd $1 && gh pr list | grep $git_branch| head -n 1| cut -f1 2>/dev/null )
    if [[ $pr_id == *"not a git repository"* ]]; then
      pr_info=""
    else
      pr_status="$(cd $1 && gh pr status |grep -A1 $pr_id| sed -n 2p | awk '{$1=$1};1')"
      if [ -n "$pr_status" ]; then
        case $pr_status in
          *failing*              ) pr_color="#[fg=black,bg=red]" ;;
          *Changes\ requested*   ) pr_color="#[fg=black,bg=red]" ;;
          *pending*              ) pr_color="#[fg=black,bg=yellow]" ;;
                               * ) pr_color="#[fg=black,bg=green]" ;;
        esac

        pr_info="${pr_color} ${pr_status} "
      else
        pr_info=""
      fi
    fi
  else
    pr_info=""
  fi
else
  pr_info=""
fi

directory="#[bg=#282a36,fg=green] $1 "

echo "$directory$git_info$pr_info"
