# update Homebrew
update
# update Formula
upgrade

install git
install rbenv
install ruby-build
install mysql
install zsh

tap sanemat/font
install ricty

# install homebrew-cask
tap phinze/homebrew-cask
install brew-cask

# Install with homebrew-casks
# Available apps: https://github.com/phinze/homebrew-cask/tree/master/Casks
cask install airmail-beta
cask install alfred
cask install android-studio
cask install genymotion
cask install appcleaner
cask install crashlytics
cask install dropbox
cask install evernote
cask install firefox
cask install google-chrome
cask install hipchat
cask install iterm2
cask install keyremap4macbook
cask install libreoffice
cask install macvim
cask install screenflow
cask install sequel-pro
cask install skype
cask install vagrant
cask install virtualbox

# remove unused files
cleanup

# allow Alfred to suggest Apps installed with cask
cask alfred link
